#!/bin/bash
#
# Author: Mike Purvis <mpurvis@clearpathrobotics.com>
#         Copyright (c) 2013, Clearpath Robotics, Inc.
# 
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions are met:
#    * Redistributions of source code must retain the above copyright
#       notice, this list of conditions and the following disclaimer.
#    * Redistributions in binary form must reproduce the above copyright
#       notice, this list of conditions and the following disclaimer in the
#       documentation and/or other materials provided with the distribution.
#    * Neither the name of Clearpath Robotics, Inc. nor the
#       names of its contributors may be used to endorse or promote products
#       derived from this software without specific prior written permission.
# 
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
# ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
# WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
# DISCLAIMED. IN NO EVENT SHALL CLEARPATH ROBOTICS, INC. BE LIABLE FOR ANY
# DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
# (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
# LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
# ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
# (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
# SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
# 
# Please send comments, questions, or patches to code@clearpathrobotics.com 

function log() {
  logger -s -p user.$1 ${@:2}
}

log info "jeeves: Using workspace setup file /home/mcecsbot/src/roboticsclub-mcecsbot/src/ros/devel/setup.bash"
source /home/mcecsbot/src/roboticsclub-mcecsbot/src/ros/devel/setup.bash
JOB_FOLDER=/etc/ros/indigo/jeeves.d 

export ROS_IP=`rosrun robot_upstart getifip eth0`
export ROS_MASTER_URI=http://$ROS_IP:11311
if [ "$ROS_IP" = "" ]; then
  log err "jeeves: No IP address on eth0, cannot roslaunch."
  exit 1
fi
log info "jeeves: Launching on interface eth0, ROS_IP=$ROS_IP, ROS_MASTER_URI=$ROS_MASTER_URI"

# If xacro files are present in job folder, generate and expand an amalgamated urdf.
XACRO_FILENAME=/tmp/jeeves.xacro
XACRO_ROBOT_NAME=$(echo "jeeves" | cut -d- -f1)
rosrun robot_upstart mkxacro $JOB_FOLDER $XACRO_ROBOT_NAME > $XACRO_FILENAME
if [[ "$?" == "0" ]]; then
  URDF_FILENAME=/tmp/jeeves.urdf
  rosrun xacro xacro $XACRO_FILENAME -o $URDF_FILENAME
  if [[ "$?" == "0" ]]; then
    log info "jeeves: Generated URDF: $URDF_FILENAME"
  else
    log warn "jeeves: URDF macro expansion failure. Robot description will not function."
  fi
  export ROBOT_URDF_FILENAME=$URDF_FILENAME
fi

# Assemble amalgamated launchfile.
LAUNCH_FILENAME=/tmp/jeeves.launch
rosrun robot_upstart mklaunch $JOB_FOLDER > $LAUNCH_FILENAME
if [[ "$?" != "0" ]]; then
  log err "jeeves: Unable to generate amalgamated launchfile."
  exit 1
fi
log info "jeeves: Generated launchfile: $LAUNCH_FILENAME"

# Warn and exit if setuidgid is missing from the system.
which setuidgid > /dev/null
if [ "$?" != "0" ]; then
  log err "jeeves: Can't launch as unprivileged user without setuidgid. Please install daemontools package."
  exit 1
fi

# Punch it.
export ROS_HOME=$(echo ~mcecsbot)/.ros

# we want logs in the standard location (~mcecsbot/.ros), so the following is commented-out
#export ROS_LOG_DIR=/tmp

# Note: we set uid and gid in jeeves.conf, so the folowing is commented-out
#setuidgid mcecsbot roslaunch $LAUNCH_FILENAME &
roslaunch $LAUNCH_FILENAME &
PID=$!

log info "jeeves: Started roslaunch as background process, PID $PID"
echo "$PID" > /tmp/jeeves.pid

wait "$PID"
