# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-03-04 08:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='QR',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('QR_ID', models.IntegerField(unique=True)),
                ('Message', models.TextField(default=b'new message')),
            ],
        ),
    ]
